INSERT INTO lesson VALUES ('1', 'test', 'test', '50');
INSERT INTO lesson VALUES ('2', 'test', 'test', '1');
INSERT INTO lesson VALUES ('00000003', 'パズル道場【図形・思考力】', 'パズル【図・思】', '50');
INSERT INTO lesson VALUES ('00000004', 'パズル道場【数】', 'パズル【数】', '50');
INSERT INTO lesson VALUES ('00000005', '反復演習ジムeトレ＆eドリル', '演習', '50');
INSERT INTO lesson VALUES ('00000006', 'パズル道場【国語】', 'パズル【国】', '50');
INSERT INTO lesson VALUES ('00000007', '東進中学NET', '中学ネット', '50');
INSERT INTO lesson VALUES ('00000008', 'デイビッド・セイン英語ジム', 'セイン', NULL);
INSERT INTO lesson VALUES ('00000009', '東大個別指導会T・MEG', 'TMEG', NULL);
INSERT INTO lesson VALUES ('00000010', 'LOGICTREE', 'LOGICTREE', NULL);
INSERT INTO lesson VALUES ('00000011', '東進衛星予備校', '東進', NULL);

INSERT INTO course VALUES ('00000001', '週１回', '1');
INSERT INTO course VALUES ('00000002', '週２回', '2');
INSERT INTO course VALUES ('00000003', '週３回', '3');

INSERT INTO grade VALUES ('1', '年少');
INSERT INTO grade VALUES ('2', '年中');
INSERT INTO grade VALUES ('3', '年長');
INSERT INTO grade VALUES ('4', '小１');
INSERT INTO grade VALUES ('5', '小２');
INSERT INTO grade VALUES ('6', '小３');
INSERT INTO grade VALUES ('7', '小４');
INSERT INTO grade VALUES ('8', '小５');
INSERT INTO grade VALUES ('9', '小６');
INSERT INTO grade VALUES ('10', '中１');
INSERT INTO grade VALUES ('11', '中２');
INSERT INTO grade VALUES ('12', '中３');
INSERT INTO grade VALUES ('13', '高１');
INSERT INTO grade VALUES ('14', '高２');
INSERT INTO grade VALUES ('15', '高３');
INSERT INTO grade VALUES ('16', '一般');
INSERT INTO grade VALUES ('17', '１年');
INSERT INTO grade VALUES ('18', '２年');
INSERT INTO grade VALUES ('19', '３年');
INSERT INTO grade VALUES ('20', '４年');
INSERT INTO grade VALUES ('21', '５年');
INSERT INTO grade VALUES ('22', '６年');
INSERT INTO grade VALUES ('23', '院生');
INSERT INTO grade VALUES ('24', '既卒');


INSERT INTO m_timed VALUES ('1', '１限', '9:00:00', '10:20:00', 'True');
INSERT INTO m_timed VALUES ('2', '２限', '10:30:00', '11:50:00', 'True');
INSERT INTO m_timed VALUES ('3', '３限', '13:00:00', '14:20:00', 'True');
INSERT INTO m_timed VALUES ('4', '４限', '14:30:00', '15:50:00', 'True');
INSERT INTO m_timed VALUES ('5', '５限', '16:00:00', '17:20:00', 'True');
INSERT INTO m_timed VALUES ('6', '６限', '17:30:00', '18:50:00', 'True');
INSERT INTO m_timed VALUES ('7', '７限', '19:00:00', '20:20:00', 'True');
INSERT INTO m_timed VALUES ('8', '８限', '20:30:00', '21:50:00', 'True');
INSERT INTO m_timed VALUES ('9', '９限', NULL, NULL, 'False');
INSERT INTO m_timed VALUES ('10', '１０限', NULL, NULL, 'False');

INSERT INTO m_timetable VALUES ('月', '1', 'False');
INSERT INTO m_timetable VALUES ('月', '2', 'False');
INSERT INTO m_timetable VALUES ('月', '3', 'False');
INSERT INTO m_timetable VALUES ('月', '4', 'False');
INSERT INTO m_timetable VALUES ('月', '5', 'True');
INSERT INTO m_timetable VALUES ('月', '6', 'True');
INSERT INTO m_timetable VALUES ('月', '7', 'True');
INSERT INTO m_timetable VALUES ('月', '8', 'True');
INSERT INTO m_timetable VALUES ('火', '1', 'False');
INSERT INTO m_timetable VALUES ('火', '2', 'False');
INSERT INTO m_timetable VALUES ('火', '3', 'False');
INSERT INTO m_timetable VALUES ('火', '4', 'False');
INSERT INTO m_timetable VALUES ('火', '5', 'True');
INSERT INTO m_timetable VALUES ('火', '6', 'True');
INSERT INTO m_timetable VALUES ('火', '7', 'True');
INSERT INTO m_timetable VALUES ('火', '8', 'True');
INSERT INTO m_timetable VALUES ('水', '1', 'False');
INSERT INTO m_timetable VALUES ('水', '2', 'False');
INSERT INTO m_timetable VALUES ('水', '3', 'False');
INSERT INTO m_timetable VALUES ('水', '4', 'False');
INSERT INTO m_timetable VALUES ('水', '5', 'True');
INSERT INTO m_timetable VALUES ('水', '6', 'True');
INSERT INTO m_timetable VALUES ('水', '7', 'True');
INSERT INTO m_timetable VALUES ('水', '8', 'True');
INSERT INTO m_timetable VALUES ('木', '1', 'False');
INSERT INTO m_timetable VALUES ('木', '2', 'False');
INSERT INTO m_timetable VALUES ('木', '3', 'False');
INSERT INTO m_timetable VALUES ('木', '4', 'False');
INSERT INTO m_timetable VALUES ('木', '5', 'True');
INSERT INTO m_timetable VALUES ('木', '6', 'True');
INSERT INTO m_timetable VALUES ('木', '7', 'True');
INSERT INTO m_timetable VALUES ('木', '8', 'True');
INSERT INTO m_timetable VALUES ('金', '1', 'False');
INSERT INTO m_timetable VALUES ('金', '2', 'False');
INSERT INTO m_timetable VALUES ('金', '3', 'False');
INSERT INTO m_timetable VALUES ('金', '4', 'False');
INSERT INTO m_timetable VALUES ('金', '5', 'True');
INSERT INTO m_timetable VALUES ('金', '6', 'True');
INSERT INTO m_timetable VALUES ('金', '7', 'True');
INSERT INTO m_timetable VALUES ('金', '8', 'True');
INSERT INTO m_timetable VALUES ('土', '1', 'True');
INSERT INTO m_timetable VALUES ('土', '2', 'True');
INSERT INTO m_timetable VALUES ('土', '3', 'True');
INSERT INTO m_timetable VALUES ('土', '4', 'True');
INSERT INTO m_timetable VALUES ('土', '5', 'True');
INSERT INTO m_timetable VALUES ('土', '6', 'True');
INSERT INTO m_timetable VALUES ('土', '7', 'True');
INSERT INTO m_timetable VALUES ('土', '8', 'True');
INSERT INTO m_timetable VALUES ('日', '1', 'False');
INSERT INTO m_timetable VALUES ('日', '2', 'False');
INSERT INTO m_timetable VALUES ('日', '3', 'False');
INSERT INTO m_timetable VALUES ('日', '4', 'False');
INSERT INTO m_timetable VALUES ('日', '5', 'False');
INSERT INTO m_timetable VALUES ('日', '6', 'False');
INSERT INTO m_timetable VALUES ('日', '7', 'False');
INSERT INTO m_timetable VALUES ('日', '8', 'False');

INSERT INTO teacher VALUES ('00000001', '渡崎 真琴', 'ワタリザキ マコト', 'female', '1998-03-10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', NULL, NULL, NULL);
INSERT INTO teacher VALUES ('00000003', '田村 天', 'タムラ タカシ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', '2021-07-12 22:39:35.395808', NULL, NULL);
INSERT INTO teacher VALUES ('00000004', '田村 天', 'タムラ タカシ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', '2021-07-12 22:40:09.321386', NULL, NULL);
INSERT INTO teacher VALUES ('00000007', '齋藤 飛鳥', 'サイトウ アスカ', NULL, '1998-08-10', '早稲田大学', '法学部', '法律学科', '21', '07044448888', 'ashurin@nogizaka.co.jp', '1508001', '東京都渋谷区', '乃木坂の主役', 'false', '2021-07-14 02:50:13.302925', NULL, NULL);
INSERT INTO teacher VALUES ('00000008', '齋藤 飛鳥', 'サイトウ アスカ', 'female', '1998-08-10', '早稲田大学', '法学部', '法律学科', '21', '07044448888', 'ashurin@nogizaka.co.jp', '1508001', '東京都渋谷区', '乃木坂の主役', 'false', '2021-07-14 02:51:33.544718', NULL, NULL);
INSERT INTO teacher VALUES ('00000009', '白石 麻衣', 'シライシ マイ', 'female', '1992-08-20', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', '2021-07-14 02:58:43.204408', NULL, NULL);
INSERT INTO teacher VALUES ('00000010', '田中 一郎', 'タナカ イチロウ', 'male', '2001-04-01', '青山学院大学', '国際教養学部', NULL, '18', '09012334567', 'tanaka@xxx.co.jp', '5559999', '東京都渋谷区南青山', NULL, 'false', '2021-07-14 21:07:59.466879', NULL, NULL);

INSERT INTO teacher_subject VALUES ('00000010', '0005');
INSERT INTO teacher_subject VALUES ('00000010', '0007');
INSERT INTO teacher_subject VALUES ('00000010', '0010');
INSERT INTO teacher_subject VALUES ('00000010', '0012');
INSERT INTO teacher_subject VALUES ('00000010', '0015');
INSERT INTO teacher_subject VALUES ('00000010', '0016');
INSERT INTO teacher_subject VALUES ('00000010', '0017');

INSERT INTO m_subject VALUES ('0001', '小学算数');
INSERT INTO m_subject VALUES ('0002', '小学国語');
INSERT INTO m_subject VALUES ('0003', '小学理科');
INSERT INTO m_subject VALUES ('0004', '小学社会');
INSERT INTO m_subject VALUES ('0005', '中学受験算数');
INSERT INTO m_subject VALUES ('0006', '中学受験国語');
INSERT INTO m_subject VALUES ('0007', '中学受験理科');
INSERT INTO m_subject VALUES ('0008', '中学受験社会');
INSERT INTO m_subject VALUES ('0009', '中学英語');
INSERT INTO m_subject VALUES ('0010', '中学数学');
INSERT INTO m_subject VALUES ('0011', '中学国語');
INSERT INTO m_subject VALUES ('0012', '中学理科');
INSERT INTO m_subject VALUES ('0013', '中学社会');
INSERT INTO m_subject VALUES ('0014', '高校英語');
INSERT INTO m_subject VALUES ('0015', '数学Ⅰ・A');
INSERT INTO m_subject VALUES ('0016', '数学Ⅱ・B');
INSERT INTO m_subject VALUES ('0017', '数学Ⅲ');
INSERT INTO m_subject VALUES ('0018', '現代文');
INSERT INTO m_subject VALUES ('0019', '古文');
INSERT INTO m_subject VALUES ('0020', '漢文');
INSERT INTO m_subject VALUES ('0021', '小論文');
INSERT INTO m_subject VALUES ('0022', '世界史');
INSERT INTO m_subject VALUES ('0023', '日本史');
INSERT INTO m_subject VALUES ('0024', '地理');
INSERT INTO m_subject VALUES ('0025', '現代社会');
INSERT INTO m_subject VALUES ('0026', '倫理');
INSERT INTO m_subject VALUES ('0027', '政治経済');
INSERT INTO m_subject VALUES ('0028', '化学');
INSERT INTO m_subject VALUES ('0029', '物理');
INSERT INTO m_subject VALUES ('0030', '生物');
INSERT INTO m_subject VALUES ('0031', '地学');

